server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/
  instance:
    prefer-ip-address: true
management:
   tracing:
      sampling:
         probability: 1.0